Fail on function? Function 'failFunction' with args () failed with status code 1
